name: Build and Test
on:
  push:
    branches: [main]
  pull_request:
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: action/checkout@2
      - name: Install Node 14.x
        uses: action/setup-node@2
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: npm clean-install
